### PR TITLE
++i; -> i++;

### PR DESCRIPTION
**Pull request by TheKodeToad**
It may be causing some problems...

### CODE REVIEW

**Review by halotroop2288 — APPROVED** [review]

**Comment by Gaming32** [comment]
What happened with [TestSwitchPatternMatching22.dec](https://github.com/Vineflower/vineflower/pull/278/files#diff-f623390cf5ee543e2cb31533397f050f29e12e0267ee0c9b8bf841555cef1de5)?

**Comment by TheKodeToad** [comment]
The steamroller happened

**Comment by Earthcomputer** [comment]
At a glance, looks like that may be due to a difference in the compiler?

**Comment by jaskarth** [comment]
This has been discussed on the socials, there's some discrepancy between the github actions and local. I would request dropping TestSwitchPatternMatching22.dec and TestSwitchPatternMatchingFuzz1.dec from the patch.

**Comment by TheKodeToad** [comment]
Ah, thanks! I've restored the files to the commit a based the branch on

**Review by Earthcomputer — APPROVED** [review]

**Review by jaskarth — APPROVED** [review]

**Comment by jaskarth** [comment]
This PR has been merged manually as commit [55eb5e3](https://github.com/Vineflower/vineflower/commit/55eb5e3e7f8bc9ca2d83c5eabd4919f1ddeae761) due to the large amount of conflicts, and as so I'll close this PR. Thank you for this!

**Comment by TheKodeToad** [comment]
Oops. Couldn't you have pushed to my branch?

**Comment by jaskarth** [comment]
It was easier to do this patch workflow style on my end, by grabbing the patchfile and fixing the diffs. The end result is the same in any case.

**Comment by TheKodeToad** [comment]
~~but GitHub PR stats :pleading_face:~~
Ah, I see

**Pull request closed without merging**
